
# Redis服务器地址
spring:
  redis:
    host: localhost
    port: 6379
    # 默认数据库
    database: 13
    # 连接超时时间(毫秒)
    timeout: 1800000
    lettuce:
      pool:
        # 连接池最大连接数(负数表示没有限制)
        max-active: 20
        # 最大阻塞等待时间(负数表示没有限制)
        max-wait: -1ms
        # 连接池中最大空闲连接
        max-idle: 5
        # 连接池中最小空闲连接
        min-idle: 0














